# Используем официальный образ Python как базовый
FROM python:3.10-slim

# Отключаем буферизацию вывода (чтобы логи сразу выводились в консоль)
ENV PYTHONUNBUFFERED=1

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Копируем файл зависимостей и устанавливаем их
COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Копируем весь проект в рабочую директорию контейнера
COPY . .

# Открываем порт 8000 (по которому будет работать приложение)
EXPOSE 8000

# Команда для запуска приложения через uvicorn
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
